### PR TITLE
MODKBEKBJ-209 - Do not capitalize contributor type

### PR DESCRIPTION
**Pull request by natali-zaitseva**
## Purpose
Updates for https://issues.folio.org/browse/MODKBEKBJ-209

## Approach
* updated ContributorsConverterPair to use a lowercase method
* updated tests

### CODE REVIEW

**Comment by natali-zaitseva** [comment]
@sduvvuri-ebsco as for `contributor type` - we use it, for instance, in POST /title and without this parameter RM API returns following error 
`{
    "errors": [
        {
            "title": "Parameter contributorsList.type can not be null or empty."
        }
    ],
    "jsonapi": {
        "version": "1.0"
    }
}`
I am not completely sure why UI has problems with a capitalized value of contributor type

**Comment by sduvvuri-ebsco** [comment]
@natali-zaitseva : Probably, my earlier comment wasn't clear. I meant whether we are getting Contributor Type in upper case or lower case from RM API so that we can just pass it through to UI. Is the casing consistent? UI just wanted to avoid additional computation on the backend which is why this story was put together. I can explain better in a call right after our stand up if thats easier.

**Comment by natali-zaitseva** [comment]
@sduvvuri-ebsco got it, thanks for the explanation. You are right, RM API returns values already in lower case, so additional call `lowerCase` for the type is not needed

**Comment by sduvvuri-ebsco** [comment]
@natali-zaitseva : Perfect. Thanks for checking.

**Pull request merged**
